--- 
after_success: 
  - pwd
  - "ls -al"
  - "mkdir codedeploy_artifact"
  - "cp infrastructure/aws/codedeploy/*.sh ."
  - "cp infrastructure/aws/codedeploy/*.yml ."
  - "zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip webapp/demo.war *.sh *.yml"
  - "ls -al"
  - "mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/"
  - "ls -al"
  - pwd
  - "cd codedeploy_artifact"
  - "ls -al"
  - pwd
  - "cd .."
  - pwd
  - "ls -al"
deploy: 
  - 
    access_key_id: $access_key_id
    bucket: $s3_bucket
    local_dir: codedeploy_artifact
    provider: s3
    region: us-east-1
    secret_access_key: $secret_access_key
    skip_cleanup: true
  - 
    access_key_id: $access_key_id
    application: $application
    bucket: $s3_bucket
    bundle_type: zip
    deployment_group: $deployment_group
    key: csye6225-web-app-$TRAVIS_JOB_NUMBER.zip
    provider: codedeploy
    region: us-east-1
    secret_access_key: $secret_access_key
    wait-until-deployed: true
install: true
jdk: 
  - oraclejdk8
language: java
script: 
  - pwd
  - "cd webapp/demo"
  - "./gradlew war"
  - "cd build/libs"
  - "ls -al"
  - "cd ../../.."
  - pwd
  - "ls -al"
sudo: false
