language: java

jdk: 
  - oraclejdk8
  
sudo: false
  
install: true

script: 
  - pwd
  - "cd webapp/demo"
  - "./gradlew war"
  - "cd build"
  - "pwd"
  - "ls -al"
  - "cd libs"
  - "ls -al"
  - "cd ../../../../"
  - pwd
  - "ls -al" 
after_success: 
  - pwd
  - "ls -al"
  - "mkdir codedeploy_artifact"
  - "cp infrastructure/aws/codedeploy/*.sh ."
  - "cp infrastructure/aws/codedeploy/*.yml ."
  - "zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip webapp/demo/build/libs/demo.war *.sh *.yml"
  - "ls -al"	
  - "mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/"
  - "ls -al"
  - pwd
  - "cd codedeploy_artifact"
  - "ls -al"
  - pwd
  - "cd .."
  - pwd
  - "ls -al"
deploy: 
  - provider: s3
    local_dir: codedeploy_artifact
    access_key_id: $access_key_id
    bucket: $s3_bucket
    region: us-east-1
    secret_access_key: $secret_access_key
    skip_cleanup: true
    wait-until-deployed: true
    acl: public_read
    on:
      branch: Assignment7-8
      
  - provider: codedeploy
    access_key_id: $access_key_id
    application: $application
    bucket: $s3_bucket
    bundle_type: zip
    deployment_group: $deployment_group
    key: csye6225-web-app-$TRAVIS_JOB_NUMBER.zip
    region: us-east-1
    secret_access_key: $secret_access_key
    wait-until-deployed: true
    on:
      branch: Assignment7-8
